name: Run daily scripts

on:
  schedule:
    - cron: '47 11 * * *'  
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  run-daily-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright  # Install playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install  # Install necessary browsers for Playwright

      - name: Run daily script
        run: |
          python player_stat1.py
          python playwrit.py
