name: Run daily scripts

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-daily-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install chromium
          python -m playwright install-deps

      - name: Run daily scripts with error handling
        run: |
          echo "Running player_stat1.py..."
          python player_stat1.py || echo "player_stat1.py failed but continuing..."
          
          echo "Running playwrit.py..."
          python playwrit.py || echo "playwrit.py failed but continuing..."

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain data/)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in data files"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push CSV updates
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "67693914+oforiik@users.noreply.github.com"
          git config --local user.name "oforiik"
          git add data/form_stats.csv data/season_stats.csv
          git commit -m "Update CSV files with daily data [$(date +'%Y-%m-%d %H:%M:%S UTC')]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: |
            *.log
            screenshots/