name: Run daily scripts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 12:17 UTC
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  run-daily-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright  # Install playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install  # Install necessary browsers for Playwright

      - name: Run daily scripts
        run: |
          python player_stat1.py
          python playwrit.py

      - name: Commit and push CSV updates if there are changes
        run: |
          git config --local user.email "67693914+oforiik@users.noreply.github.com"
          git config --local user.name "oforiik"
          git add data/form_stats.csv data/season_stats.csv
          
          # Only commit if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update CSV files with daily data"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for permissions
